apiVersion: v1
kind: ConfigMap
metadata:
  name: contractus-webapp
  namespace: contractus
  labels:
    {{- include "contractus.labels" . | nindent 4 }}
data:
{{- with .Values.deployment.container.variables.configMap }}
  {{- toYaml . | nindent 2 }}
{{- end }}
