apiVersion: v1
kind: Secret
metadata:
  name: contractus-webapp
  namespace: contractus
  labels:
    {{- include "contractus.labels" . | nindent 4 }}
type: Opaque
data:
{{- with .Values.deployment.container.variables.secret }}
  {{- toYaml . | nindent 2 }}
{{- end }}
