apiVersion: v1
kind: Service
metadata:
  name: contractus-webapp
  namespace: contractus
  labels:
    {{- include "contractus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "contractus.selectorLabels" . | nindent 4 }}
