/*##############################

NÃO FUNCIONOU COM O LOOPBACK, QUE  COLOCA O SCHEMA.TABELA ENTRE ASPAS E O POSTGRES DIZ QUE A TABELA (RELATION)
NÃO EXISTE. TEMOS QUE ACHAR UMA FORMA DE O LOOPBACK NÃO COLOCAR AS ASPAS (FUNCIONA) OU ALGUM RECURSO NO POSTGRES
DE FORMA QUE O SCHEMA.TABELA ENTRE ASPAS SEJA RECONHECIDO

################################
-- SCHEMA: contractusapp

-- DROP SCHEMA contractusapp ;
CREATE SCHEMA contractusapp
    AUTHORIZATION contractusapp;


-- SEQUENCE: contractusapp.SQ_TB_PAPEL"

-- DROP SEQUENCE contractusapp.SQ_TB_PAPEL";

CREATE SEQUENCE contractusapp.SQ_TB_PAPEL
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE contractusapp.SQ_TB_PAPEL
    OWNER TO contractusapp;

-- Table: contractusapp.TB_PAPEL"

-- DROP TABLE contractusapp.TB_PAPEL";

CREATE TABLE contractusapp.TB_PAPEL
(
    ID_PAPEL integer NOT NULL DEFAULT nextval('contractusapp.SQ_TB_PAPEL'::regclass),
    DE_PAPEL text COLLATE pg_catalog.default NOT NULL,
    CONSTRAINT PK_TB_PAPEL PRIMARY KEY (ID_PAPEL)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE contractusapp.TB_PAPEL
    OWNER TO contractusapp;


-- SEQUENCE: contractusapp.SQ_TB_FORNECEDOR

-- DROP SEQUENCE contractusapp.SQ_TB_FORNECEDOR;

CREATE SEQUENCE contractusapp.SQ_TB_FORNECEDOR
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE contractusapp.SQ_TB_FORNECEDOR
    OWNER TO contractusapp;

-- Table: contractusapp.TB_FORNECEDOR

-- DROP TABLE contractusapp.TB_FORNECEDOR;

CREATE TABLE contractusapp.TB_FORNECEDOR
(
    "ID_FORNECEDOR" integer NOT NULL DEFAULT nextval('contractusapp.SQ_TB_FORNECEDOR'::regclass),
    "NR_CNPJ_FORNECEDOR" bigint NOT NULL,
    "NM_RAZAO_SOCIAL" text COLLATE pg_catalog."default" NOT NULL,
    "NM_APELIDO" text COLLATE pg_catalog."default" NOT NULL,
    "TX_ENDERECO" text COLLATE pg_catalog."default",
    "NM_BAIRRO" text COLLATE pg_catalog."default",
    "NM_CIDADE" text COLLATE pg_catalog."default",
    "SG_UF" text COLLATE pg_catalog."default",
    "TX_EMAIL" text COLLATE pg_catalog."default",
    "NR_TELEFONE" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_TB_FORNECEDOR" PRIMARY KEY ("ID_FORNECEDOR")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE contractusapp.TB_FORNECEDOR
    OWNER TO contractusapp;



-- SEQUENCE: contractusapp.SQ_TB_CONTRATO"

-- DROP SEQUENCE contractusapp.SQ_TB_CONTRATO";

CREATE SEQUENCE contractusapp.SQ_TB_CONTRATO
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE contractusapp.SQ_TB_CONTRATO
    OWNER TO contractusapp;

-- Table: contractusapp.TB_CONTRATO

-- DROP TABLE contractusapp.TB_CONTRATO;

CREATE TABLE contractusapp.TB_CONTRATO
(
    "ID_CONTRATO" integer NOT NULL DEFAULT nextval('contractusapp.SQ_TB_CONTRATO'::regclass),
    "NR_CONTRATO" integer NOT NULL,
    "NR_ANO_CONTRATO" integer NOT NULL,
    "DT_INICIO_VIGENCIA" timestamp without time zone NOT NULL,
    "DT_FIM_VIGENCIA" timestamp with time zone,
    "DT_ASSINATURA" timestamp with time zone,
    "NR_PROCESSO_LICITACAO" integer NOT NULL,
    "NR_PROCESSO_ORDENS_SERVICO" text COLLATE pg_catalog."default",
    "NR_PROCESSO_PAGAMENTOS" text COLLATE pg_catalog."default",
    "NR_TERMO_REFERENCIA_SEI" integer,
    "NR_CONTRATO_SEI" integer,
    "idfornecedor" integer NOT NULL, --############## TODO: VER COMO CUSTOMIZAR O NOME DA COLUNA FK (talvez deixar sem o belongsTo)
    CONSTRAINT "PK_TB_CONTRATO" PRIMARY KEY ("ID_CONTRATO"),
    CONSTRAINT "FK_CONTRATO_FORNECEDOR" FOREIGN KEY ("idFornecedor")
        REFERENCES contractusapp.TB_FORNECEDOR ("ID_FORNECEDOR") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE contractusapp.TB_CONTRATO
    OWNER TO contractusapp;


-- SEQUENCE: contractusapp.SQ_TB_TIPO_ORDEM_SERVICO_CONTRATO

-- DROP SEQUENCE contractusapp.SQ_TB_TIPO_ORDEM_SERVICO_CONTRATO;

CREATE SEQUENCE contractusapp.SQ_TB_TIPO_ORDEM_SERVICO_CONTRATO
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE contractusapp.SQ_TB_TIPO_ORDEM_SERVICO_CONTRATO
    OWNER TO contractusapp;

-- Table: contractusapp.TB_TIPO_ORDEM_SERVICO_CONTRATO

-- DROP TABLE contractusapp.TB_TIPO_ORDEM_SERVICO_CONTRATO;

CREATE TABLE contractusapp.TB_TIPO_ORDEM_SERVICO_CONTRATO
(
    "ID_TIPO_ORDEM_SERVICO" integer NOT NULL DEFAULT nextval('contractusapp.SQ_TB_TIPO_ORDEM_SERVICO_CONTRATO'::regclass),
    "ID_CONTRATO" integer NOT NULL,
    "DE_TIPO_ORDEM_SERVICO" text COLLATE pg_catalog."default" NOT NULL,
    "IN_TERMO_ACEITACAO_EMITIDO_POR_ETAPA" boolean NOT NULL,
    "DE_TEMPLATE_ORDEM_SERVICO" text COLLATE pg_catalog."default",
    "DE_TEMPLATE_TERMO_ACEITACAO" text COLLATE pg_catalog."default",
    "DE_TEMPLATE_TRP" text COLLATE pg_catalog."default",
    "DE_TEMPLATE_TRD" text COLLATE pg_catalog."default",
    "SG_UNIDADE_GARANTIA" text COLLATE pg_catalog."default" NOT NULL,
    "NR_TEMPO_GARANTIA" integer NOT NULL,
    CONSTRAINT "PK_TB_TIPO_ORDEM_SERVICO_CONTRATO" PRIMARY KEY ("ID_TIPO_ORDEM_SERVICO"),
    CONSTRAINT "FK_TIPO_ORDEM_SERVICO_CONTRATO" FOREIGN KEY ("ID_CONTRATO")
        REFERENCES contractusapp.TB_CONTRATO ("ID_CONTRATO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE contractusapp.TB_TIPO_ORDEM_SERVICO_CONTRATO
    OWNER TO contractusapp;

-- SEQUENCE: contractusapp.SQ_TB_ENTREGAVEL_TIPO_ORDEM_SERVICO

-- DROP SEQUENCE contractusapp.SQ_TB_ENTREGAVEL_TIPO_ORDEM_SERVICO;

CREATE SEQUENCE contractusapp.SQ_TB_ENTREGAVEL_TIPO_ORDEM_SERVICO
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE contractusapp.SQ_TB_ENTREGAVEL_TIPO_ORDEM_SERVICO
    OWNER TO contractusapp;

-- Table: contractusapp.TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO

-- DROP TABLE contractusapp.TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO;

CREATE TABLE contractusapp.TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO
(
    "ID_ENTREGAVEL_TIPO_ORDEM_SERVICO" integer NOT NULL DEFAULT nextval('contractusapp.SQ_TB_ENTREGAVEL_TIPO_ORDEM_SERVICO'::regclass),
    "ID_TIPO_ORDEM_SERVICO" integer NOT NULL,
    "DE_ENTREGAVEL" text COLLATE pg_catalog."default" NOT NULL,
    "NR_ORDEM" integer,
    CONSTRAINT "PK_TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO" PRIMARY KEY ("ID_ENTREGAVEL_TIPO_ORDEM_SERVICO"),
    CONSTRAINT "FK_ENTREGAVEL_TIPO_ORDEM_SERVICO" FOREIGN KEY ("ID_TIPO_ORDEM_SERVICO")
        REFERENCES contractusapp.TB_TIPO_ORDEM_SERVICO_CONTRATO ("ID_TIPO_ORDEM_SERVICO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE contractusapp.TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO
    OWNER TO contractusapp;

-- SEQUENCE: contractusapp.SQ_TB_INDICADOR_TIPO_ORDEM_SERVICO

-- DROP SEQUENCE contractusapp.SQ_TB_INDICADOR_TIPO_ORDEM_SERVICO;

CREATE SEQUENCE contractusapp.SQ_TB_INDICADOR_TIPO_ORDEM_SERVICO
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE contractusapp.SQ_TB_INDICADOR_TIPO_ORDEM_SERVICO
    OWNER TO contractusapp;


-- Table: contractusapp.TB_INDICADOR_TIPO_ORDEM_SERVICO

-- DROP TABLE contractusapp.TB_INDICADOR_TIPO_ORDEM_SERVICO;

CREATE TABLE contractusapp.TB_INDICADOR_TIPO_ORDEM_SERVICO
(
    "ID_INDICADOR" integer NOT NULL DEFAULT nextval('contractusapp.SQ_TB_INDICADOR_TIPO_ORDEM_SERVICO'::regclass),
    "SG_INDICADOR" text COLLATE pg_catalog."default" NOT NULL,
    "DE_INDICADOR" text COLLATE pg_catalog."default" NOT NULL,
    "DE_FORMULA_INDICADOR" text COLLATE pg_catalog."default",
    "ID_TIPO_ORDEM_SERVICO" integer,
    CONSTRAINT "PK_TB_INDICADOR_TIPO_ORDEM_SERVICO" PRIMARY KEY ("ID_INDICADOR"),
    CONSTRAINT "FK_INDICADOR_TIPO_ORDEM_SERVICO" FOREIGN KEY ("ID_TIPO_ORDEM_SERVICO")
        REFERENCES contractusapp.TB_TIPO_ORDEM_SERVICO_CONTRATO ("ID_TIPO_ORDEM_SERVICO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE contractusapp.TB_INDICADOR_TIPO_ORDEM_SERVICO
    OWNER TO contractusapp;


-- SEQUENCE: contractusapp.SQ_TB_PAPEL_CONTRATO

-- DROP SEQUENCE contractusapp.SQ_TB_PAPEL_CONTRATO;

CREATE SEQUENCE contractusapp.SQ_TB_PAPEL_CONTRATO
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE contractusapp.SQ_TB_PAPEL_CONTRATO
    OWNER TO contractusapp;

-- Table: contractusapp.TB_PAPEL_CONTRATO

-- DROP TABLE contractusapp.TB_PAPEL_CONTRATO;

CREATE TABLE contractusapp.TB_PAPEL_CONTRATO
(
    "ID_PAPEL_CONTRATO" integer NOT NULL DEFAULT nextval('contractusapp.SQ_TB_PAPEL_CONTRATO'::regclass),
    "ID_CONTRATO" integer NOT NULL,
    "ID_PAPEL"  integer NOT NULL,
    "DT_INICIO" timestamp with time zone NOT NULL,
    "DT_FIM" timestamp with time zone,
    "NM_DONO_PAPEL" text COLLATE pg_catalog."default" NOT NULL,
    "NR_CPF_DONO_PAPEL"  text COLLATE pg_catalog."default" NULL,
    "NR_SIAPE_DONO_PAPEL" text COLLATE pg_catalog."default" NULL,
    CONSTRAINT "PK_TB_PAPEL_CONTRATO PRIMARY" KEY ("ID_PAPEL_CONTRATO"),
    CONSTRAINT "FK_PAPEL_CONTRATO_CONTRATO" FOREIGN KEY ("ID_CONTRATO")
        REFERENCES contractusapp.TB_CONTRATO ("ID_CONTRATO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "FK_PAPEL_CONTRATO_PAPEL" FOREIGN KEY ("ID_PAPEL")
        REFERENCES contractusapp.TB_PAPEL ("ID_PAPEL") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE contractusapp.TB_PAPEL_CONTRATO
    OWNER TO contractusapp;


-- SEQUENCE: contractusapp.SQ_TB_METRICA_CONTRATO

-- DROP SEQUENCE contractusapp.SQ_TB_METRICA_CONTRATO;

CREATE SEQUENCE contractusapp.SQ_TB_METRICA_CONTRATO
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE contractusapp.SQ_TB_METRICA_CONTRATO
    OWNER TO contractusapp;


-- Table: contractusapp.TB_METRICA_CONTRATO

-- DROP TABLE contractusapp.TB_METRICA_CONTRATO;

CREATE TABLE contractusapp.TB_METRICA_CONTRATO
(
    "ID_METRICA_CONTRATO" integer NOT NULL DEFAULT nextval('contractusapp.SQ_TB_METRICA_CONTRATO'::regclass),
    "ID_CONTRATO" integer NOT NULL,
    "SG_METRICA" text COLLATE pg_catalog."default" NOT NULL,
    "DE_METRICA" text COLLATE pg_catalog."default" NOT NULL,
    "DT_INICIO" timestamp with time zone NOT NULL,
    "DT_FIM" timestamp with time zone,
    "VL_UNITARIO" numeric(10,2) NOT NULL,
    CONSTRAINT "PK_TB_METRICA_CONTRATO PRIMARY" KEY ("ID_METRICA_CONTRATO"),
    CONSTRAINT "FK_METRICA_CONTRATO" FOREIGN KEY ("ID_CONTRATO")
        REFERENCES contractusapp.TB_CONTRATO ("ID_CONTRATO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE contractusapp.TB_METRICA_CONTRATO
    OWNER TO contractusapp;


-- SEQUENCE: contractusapp.SQ_TB_ORDEM_SERVICO

-- DROP SEQUENCE contractusapp.SQ_TB_ORDEM_SERVICO;

CREATE SEQUENCE contractusapp.SQ_TB_ORDEM_SERVICO
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE contractusapp.SQ_TB_ORDEM_SERVICO
    OWNER TO contractusapp;

-- SEQUENCE: contractusapp.SQ_SANCAO_INDICADOR_CONTRATO

-- DROP SEQUENCE contractusapp.SQ_SANCAO_INDICADOR_CONTRATO;

CREATE SEQUENCE contractusapp.SQ_SANCAO_INDICADOR_CONTRATO
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE contractusapp.SQ_SANCAO_INDICADOR_CONTRATO
    OWNER TO contractusapp;


-- Table: contractusapp.TB_SANCAO_INDICADOR_CONTRATO

-- DROP TABLE contractusapp.TB_SANCAO_INDICADOR_CONTRATO;

CREATE TABLE contractusapp.TB_SANCAO_INDICADOR_CONTRATO
(
    "ID_SANCAO_INDICADOR_CONTRATO" integer NOT NULL DEFAULT nextval('contractusapp.SQ_SANCAO_INDICADOR_CONTRATO'::regclass),
    "ID_INDICADOR" integer NOT NULL,
    "VL_INDICADOR" integer NOT NULL,
    "VL_PERCENTUAL_GLOSA" integer NOT NULL,
    "ID_TIPO_ORDEM_SERVICO" integer,
    CONSTRAINT "PK_TB_SANCAO_INDICADOR_CONTRATO" PRIMARY KEY ("ID_SANCAO_INDICADOR_CONTRATO"),
    CONSTRAINT "FK_SANCAO_INDICADOR_CONTRATO" FOREIGN KEY ("ID_INDICADOR")
        REFERENCES contractusapp.TB_INDICADOR_TIPO_ORDEM_SERVICO ("ID_INDICADOR") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE contractusapp.TB_SANCAO_INDICADOR_CONTRATO
    OWNER TO contractusapp;


-- Table: contractusapp.TB_ORDEM_SERVICO

-- DROP TABLE contractusapp.TB_ORDEM_SERVICO;

CREATE TABLE contractusapp.TB_ORDEM_SERVICO
(
    "ID_ORDEM_SERVICO" integer NOT NULL DEFAULT nextval('contractusapp.SQ_TB_ORDEM_SERVICO'::regclass),
    "ID_CONTRATO" integer NOT NULL,
    "NR_ORDEM_SERVICO" integer,
    "IN_EMERGENCIAL" boolean NOT NULL,
    "ID_TIPO_ORDEM_SERVICO" integer NOT NULL,
    "DT_EMISSAO" timestamp with time zone,
    "ID_PROJETO" text COLLATE pg_catalog."default",
    "ID_PRODUTO" text COLLATE pg_catalog."default",
    "NR_CPF_REQUISITANTE" text COLLATE pg_catalog."default",
    "NM_REQUISITANTE" text COLLATE pg_catalog."default" NOT NULL,
    "NR_CPF_FISCAL_TECNICO" text COLLATE pg_catalog."default",
    "NM_FISCAL_TECNICO" text COLLATE pg_catalog."default" NOT NULL,
    "NR_ORDEM_SERVICO_SEI" integer,
    "NR_TERMO_RECEBIMENTO_DEFINITIVO_SEI" integer,
    "DT_CANCELAMENTO" timestamp with time zone,
    CONSTRAINT "PK_TB_ORDEM_SERVICO" PRIMARY KEY ("ID_ORDEM_SERVICO"),
    CONSTRAINT "FK_ORDEM_SERVICO_CONTRATO" FOREIGN KEY ("ID_CONTRATO")
        REFERENCES contractusapp.TB_CONTRATO ("ID_CONTRATO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "FK_ORDEM_SERVICO_TIPO_ORDEM_SERVICO" FOREIGN KEY ("ID_TIPO_ORDEM_SERVICO")
        REFERENCES contractusapp.TB_TIPO_ORDEM_SERVICO_CONTRATO ("ID_TIPO_ORDEM_SERVICO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE contractusapp.TB_ORDEM_SERVICO
    OWNER TO contractusapp;

-- SEQUENCE: contractusapp.SQ_TB_ITEM_ORDEM_SERVICO"

-- DROP SEQUENCE contractusapp.SQ_TB_ITEM_ORDEM_SERVICO";

CREATE SEQUENCE contractusapp.SQ_TB_ITEM_ORDEM_SERVICO
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE contractusapp.SQ_TB_ITEM_ORDEM_SERVICO
    OWNER TO contractusapp;


-- Table: contractusapp.TB_ITEM_ORDEM_SERVICO"

-- DROP TABLE contractusapp.TB_ITEM_ORDEM_SERVICO";

CREATE TABLE contractusapp.TB_ITEM_ORDEM_SERVICO
(
    "ID_ITEM_ORDEM_SERVICO" integer NOT NULL DEFAULT nextval('contractusapp.SQ_TB_ITEM_ORDEM_SERVICO'::regclass),
    "ID_ORDEM_SERVICO" integer NOT NULL,
    "DE_ITEM" text COLLATE pg_catalog."default" NOT NULL,
    "SG_METRICA" text COLLATE pg_catalog."default" NOT NULL,
    "QT_ESTIMADA" numeric(10,2) NOT NULL,
    "VL_UNITARIO_ESTIMADO" numeric(10,2) NOT NULL,
    "QT_REAL" numeric(10,2),
    "VL_UNITARIO_REAL" numeric(10,2),
    "IN_CANCELADO" boolean,
    CONSTRAINT "PK_TB_ITEM_ORDEM_SERVICO" PRIMARY KEY ("ID_ITEM_ORDEM_SERVICO"),
    CONSTRAINT "FK_ITEM_ORDEM_SERVICO" FOREIGN KEY ("ID_ORDEM_SERVICO")
        REFERENCES contractusapp.TB_ORDEM_SERVICO ("ID_ORDEM_SERVICO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE contractusapp.TB_ITEM_ORDEM_SERVICO
    OWNER TO contractusapp;

-- SEQUENCE: contractusapp.SQ_TB_ETAPA_ORDEM_SERVICO"

-- DROP SEQUENCE contractusapp.SQ_TB_ETAPA_ORDEM_SERVICO";

CREATE SEQUENCE contractusapp.SQ_TB_ETAPA_ORDEM_SERVICO
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE contractusapp.SQ_TB_ETAPA_ORDEM_SERVICO
    OWNER TO contractusapp;


-- Table: contractusapp.TB_ETAPA_ORDEM_SERVICO"

-- DROP TABLE contractusapp.TB_ETAPA_ORDEM_SERVICO";

CREATE TABLE contractusapp.TB_ETAPA_ORDEM_SERVICO
(
    "ID_ETAPA_ORDEM_SERVICO" integer NOT NULL DEFAULT nextval('contractusapp.SQ_TB_ETAPA_ORDEM_SERVICO'::regclass),
    "NM_ETAPA" text COLLATE pg_catalog."default" NOT NULL,
    "DT_INICIO_PLANEJADA" timestamp with time zone NOT NULL,
    "DT_FIM_PLANEJADA" timestamp with time zone NOT NULL,
    "DT_INICIO_REAL" timestamp with time zone,
    "DT_FIM_REAL" timestamp with time zone,
    "ID_ORDEM_SERVICO" integer,
    CONSTRAINT "PK_TB_ETAPA_ORDEM_SERVICO" PRIMARY KEY ("ID_ETAPA_ORDEM_SERVICO"),
    CONSTRAINT "FK_ETAPA_ORDEM_SERVICO" FOREIGN KEY ("ID_ORDEM_SERVICO")
        REFERENCES contractusapp.TB_ORDEM_SERVICO ("ID_ORDEM_SERVICO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE contractusapp.TB_ETAPA_ORDEM_SERVICO
    OWNER TO contractusapp;

-- SEQUENCE: contractusapp.SQ_TB_ENTREGAVEL_ORDEM_SERVICO"

-- DROP SEQUENCE contractusapp.SQ_TB_ENTREGAVEL_ORDEM_SERVICO";

CREATE SEQUENCE contractusapp.SQ_TB_ENTREGAVEL_ORDEM_SERVICO
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE contractusapp.SQ_TB_ENTREGAVEL_ORDEM_SERVICO
    OWNER TO contractusapp;


-- Table: contractusapp.TB_ENTREGAVEL_ORDEM_SERVICO

-- DROP TABLE contractusapp.TB_ENTREGAVEL_ORDEM_SERVICO;

CREATE TABLE contractusapp.TB_ENTREGAVEL_ORDEM_SERVICO
(
    "ID_ENTREGAVEL_ORDEM_SERVICO" integer NOT NULL DEFAULT nextval('contractusapp.SQ_TB_ENTREGAVEL_ORDEM_SERVICO'::regclass),
    "DE_ENTREGAVEL" text COLLATE pg_catalog."default" NOT NULL,
    "DE_LINK_EVIDENCIA" text COLLATE pg_catalog."default",
    "NR_ORDEM" integer,
    "ID_ORDEM_SERVICO" integer,
    CONSTRAINT "PK_TB_ENTREGAVEL_ORDEM_SERVICO" PRIMARY KEY ("ID_ENTREGAVEL_ORDEM_SERVICO"),
    CONSTRAINT "FK_ENTREGAVEL_ORDEM_SERVICO" FOREIGN KEY ("ID_ORDEM_SERVICO")
        REFERENCES contractusapp.TB_ORDEM_SERVICO ("ID_ORDEM_SERVICO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE contractusapp.TB_ENTREGAVEL_ORDEM_SERVICO
    OWNER TO contractusapp;


-- SEQUENCE: contractusapp.SQ_TB_INDICADOR_ORDEM_SERVICO"

-- DROP SEQUENCE contractusapp.SQ_TB_INDICADOR_ORDEM_SERVICO";

CREATE SEQUENCE contractusapp.SQ_TB_INDICADOR_ORDEM_SERVICO
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE contractusapp.SQ_TB_INDICADOR_ORDEM_SERVICO
    OWNER TO contractusapp;


-- Table: contractusapp.TB_INDICADOR_ORDEM_SERVICO"

-- DROP TABLE contractusapp.TB_INDICADOR_ORDEM_SERVICO";

CREATE TABLE contractusapp.TB_INDICADOR_ORDEM_SERVICO
(
    "ID_INDICADOR_ORDEM_SERVICO" integer NOT NULL DEFAULT nextval('contractusapp.SQ_TB_INDICADOR_ORDEM_SERVICO'::regclass),
    "ID_INDICADOR" integer NOT NULL,
    "VL_INDICADOR_APURADO" integer NOT NULL,
    "VL_GLOSA" integer NOT NULL,
    "ID_ORDEM_SERVICO" integer,
    CONSTRAINT "PK_TB_INDICADOR_ORDEM_SERVICO" PRIMARY KEY ("ID_INDICADOR_ORDEM_SERVICO"),
    CONSTRAINT "FK_INDICADOR_ORDEM_SERVICO" FOREIGN KEY ("ID_ORDEM_SERVICO")
        REFERENCES contractusapp.TB_ORDEM_SERVICO ("ID_ORDEM_SERVICO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE contractusapp.TB_INDICADOR_ORDEM_SERVICO
    OWNER TO contractusapp;

--GRANT ALL PRIVILEGES ON DATABASE contractusapp TO contractusapp;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA contractusapp TO contractusapp;

GRANT ALL ON DATABASE contractusapp TO contractusapp;
GRANT ALL ON DATABASE contractusapp TO postgres;
GRANT TEMPORARY, CONNECT ON DATABASE contractusapp TO PUBLIC;
