\c contractusapp

-- ÁREAS
INSERT INTO contractusapp."TB_AREA_REQUISITANTE"(
	"NM_AREA_REQUISITANTE", "SG_AREA_REQUISITANTE", "NR_PROCESSO_ORDENS_SERVICO_SEI", "NR_BLOCO_ASSINATURAS_SEI")
	VALUES ('Superintendência de Registro', 'SRE','01416.022861/2017-86', 4279);
INSERT INTO contractusapp."TB_AREA_REQUISITANTE"(
	"NM_AREA_REQUISITANTE", "SG_AREA_REQUISITANTE", "NR_PROCESSO_ORDENS_SERVICO_SEI", "NR_BLOCO_ASSINATURAS_SEI")
	VALUES ('Superintendência de Fiscalização', 'SFI','01416.022861/2017-86', 4279);
INSERT INTO contractusapp."TB_AREA_REQUISITANTE"(
	"NM_AREA_REQUISITANTE", "SG_AREA_REQUISITANTE", "NR_PROCESSO_ORDENS_SERVICO_SEI", "NR_BLOCO_ASSINATURAS_SEI")
	VALUES ('Superintendência de Fomento', 'SFO','01416.022861/2017-86', 4279);
INSERT INTO contractusapp."TB_AREA_REQUISITANTE"(
	"NM_AREA_REQUISITANTE", "SG_AREA_REQUISITANTE", "NR_PROCESSO_ORDENS_SERVICO_SEI", "NR_BLOCO_ASSINATURAS_SEI")
	VALUES ('Superintendência de Desenvolvimento Econômico','SDE','01416.022861/2017-86', 4279);
INSERT INTO contractusapp."TB_AREA_REQUISITANTE"(
	"NM_AREA_REQUISITANTE", "SG_AREA_REQUISITANTE", "NR_PROCESSO_ORDENS_SERVICO_SEI", "NR_BLOCO_ASSINATURAS_SEI")
	VALUES ('Superintendência de Prestação de Contas' ,'SPR','01416.022861/2017-86', null);
INSERT INTO contractusapp."TB_AREA_REQUISITANTE"(
	"NM_AREA_REQUISITANTE", "SG_AREA_REQUISITANTE", "NR_PROCESSO_ORDENS_SERVICO_SEI", "NR_BLOCO_ASSINATURAS_SEI")
	VALUES ('Secretaria de Gestão Interna' ,'SGI','01416.008023/2019-61', null);

-- FORNECEDOR
INSERT INTO contractusapp."TB_FORNECEDOR"(
	"NR_CNPJ_FORNECEDOR", "NM_RAZAO_SOCIAL", "NM_APELIDO", "TX_ENDERECO", "NM_BAIRRO", "NM_CIDADE", "SG_UF", "TX_EMAIL", "NR_TELEFONE")
	VALUES ('11777162000157', 'BASIS TECNOLOGIA DA INFORMACAO S/A', 'BASIS', 'SCS Quadra 08, Venâncio Shopping Bloco B-50, 8° andar, Salas 824 a 842 (pares)', 'ASA SUL', 'BRASÍLIA', 'DF', 'comercial@basis.com.br', '+55 61 3224-1661');

-- PAPEL
INSERT INTO contractusapp."TB_PAPEL"("DE_PAPEL")
	VALUES ('Fiscal Requisitante');
	INSERT INTO contractusapp."TB_PAPEL"("DE_PAPEL")
	VALUES ('Fiscal Administrativo');
	INSERT INTO contractusapp."TB_PAPEL"("DE_PAPEL")
	VALUES ('Fiscal Técnico');
INSERT INTO contractusapp."TB_PAPEL"("DE_PAPEL")
	VALUES ('Preposto');

-- CONTRATO
INSERT INTO contractusapp."TB_CONTRATO"(
	 "NR_CONTRATO", "NR_ANO_CONTRATO", "DT_INICIO_VIGENCIA", "DT_FIM_VIGENCIA", "DT_ASSINATURA", "NR_PROCESSO_LICITACAO", "NR_PROCESSO_PAGAMENTOS", "NR_TERMO_REFERENCIA_SEI", "NR_CONTRATO_SEI","ID_FORNECEDOR")
	VALUES ( 11, 2019, '06/06/2019', '06/06/2019', '06/06/2019', '01416.000531/2019-00', '01416.011089/2019-39', 1264426, 1332402, 1);

INSERT INTO contractusapp."TB_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_CONTRATO", "DE_TIPO_ORDEM_SERVICO", "IN_TERMO_ACEITACAO_EMITIDO_POR_ETAPA", "DE_TEMPLATE_ORDEM_SERVICO", "DE_TEMPLATE_TERMO_ACEITACAO", "DE_TEMPLATE_TRP", "DE_TEMPLATE_TRD", "SG_UNIDADE_GARANTIA", "NR_TEMPO_GARANTIA", "NR_DIAS_EMISSAO_TRD")
	VALUES ( 1, 'Diagnóstico', false, '', '', '', '', 'M', 12, 15);

	INSERT INTO contractusapp."TB_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_CONTRATO", "DE_TIPO_ORDEM_SERVICO", "IN_TERMO_ACEITACAO_EMITIDO_POR_ETAPA", "DE_TEMPLATE_ORDEM_SERVICO", "DE_TEMPLATE_TERMO_ACEITACAO", "DE_TEMPLATE_TRP", "DE_TEMPLATE_TRD", "SG_UNIDADE_GARANTIA", "NR_TEMPO_GARANTIA", "NR_DIAS_EMISSAO_TRD")
	VALUES ( 1, 'Desenvolvimento', true, '', '', '', '', 'M', 12, 45);
	INSERT INTO contractusapp."TB_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_CONTRATO", "DE_TIPO_ORDEM_SERVICO", "IN_TERMO_ACEITACAO_EMITIDO_POR_ETAPA", "DE_TEMPLATE_ORDEM_SERVICO", "DE_TEMPLATE_TERMO_ACEITACAO", "DE_TEMPLATE_TRP", "DE_TEMPLATE_TRD", "SG_UNIDADE_GARANTIA", "NR_TEMPO_GARANTIA", "NR_DIAS_EMISSAO_TRD")
	VALUES ( 1, 'Manutenção', true, '', '', '', '', 'M', 12, 45);

INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (1, 'Documento de Visão', 1);
	INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (1, 'Documento de Arquitetura', 2);
	INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (1, 'Contagem Estimativa de Pontos de Função', 3);

	INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (2, 'Código-fonte final da release', 1);
	INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (2, 'Dockerfile, Docker Compose, scripts de build, deploy e banco de dados', 2);
	INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (2, 'Testes unitários automatizados e suas evidências', 3);
	INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (2, 'Testes de integração automatizados e suas evidências', 4);
		INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (2, 'Testes de interface automatizados e suas evidências', 5);
			INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (2, 'Smoke tests para as funcionalidades priorizadas pelo Dono do Produto', 6);
			INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (2, 'Modelo de dados', 7);
	INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (2, 'Contagem FInal de Pontos de Função', 8);



		INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (3, 'Código-fonte final da release', 1);
	INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (3, 'Dockerfile, Docker Compose, scripts de build, deploy e banco de dados', 2);
	INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (3, 'Testes unitários automatizados e suas evidências', 3);
	INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (3, 'Testes de integração automatizados e suas evidências', 4);
		INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (3, 'Testes de interface automatizados e suas evidências', 5);
			INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (3, 'Smoke tests para as funcionalidades priorizadas pelo Dono do Produto', 6);
			INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (3, 'Modelo de dados', 7);
	INSERT INTO contractusapp."TB_ENTREGAVEL_TIPO_ORDEM_SERVICO_CONTRATO"(
	 "ID_TIPO_ORDEM_SERVICO", "DE_ENTREGAVEL", "NR_ORDEM")
	VALUES (3, 'Contagem FInal de Pontos de Função', 8);


INSERT INTO contractusapp."TB_METRICA_CONTRATO"(
	"ID_CONTRATO", "SG_METRICA", "DE_METRICA", "DT_INICIO", "DT_FIM", "VL_UNITARIO")
	VALUES (1, 'PF', 'Pontos de Função', '06/06/2019', null,510.42);

INSERT INTO contractusapp."TB_ETAPA_TIPO_ORDEM_SERVICO_CONTRATO"(
	"ID_TIPO_ORDEM_SERVICO", "DE_ETAPA", "NR_DIAS_UTEIS_DURACAO", "NR_ORDEM")
	VALUES (1, 'Única', 10, 1);

	INSERT INTO contractusapp."TB_ETAPA_TIPO_ORDEM_SERVICO_CONTRATO"(
	"ID_TIPO_ORDEM_SERVICO", "DE_ETAPA", "NR_DIAS_UTEIS_DURACAO", "NR_ORDEM")
	VALUES (2, 'Sprint 0 - Iniciação', 10, 1);
	INSERT INTO contractusapp."TB_ETAPA_TIPO_ORDEM_SERVICO_CONTRATO"(
	"ID_TIPO_ORDEM_SERVICO", "DE_ETAPA", "NR_DIAS_UTEIS_DURACAO", "NR_ORDEM")
	VALUES (2, 'Sprint 1', 10, 2);
	INSERT INTO contractusapp."TB_ETAPA_TIPO_ORDEM_SERVICO_CONTRATO"(
	"ID_TIPO_ORDEM_SERVICO", "DE_ETAPA", "NR_DIAS_UTEIS_DURACAO", "NR_ORDEM")
	VALUES (2, 'Sprint 2', 10, 3);
	INSERT INTO contractusapp."TB_ETAPA_TIPO_ORDEM_SERVICO_CONTRATO"(
	"ID_TIPO_ORDEM_SERVICO", "DE_ETAPA", "NR_DIAS_UTEIS_DURACAO", "NR_ORDEM")
	VALUES (2, 'Sprint 3', 10, 4);
	INSERT INTO contractusapp."TB_ETAPA_TIPO_ORDEM_SERVICO_CONTRATO"(
	"ID_TIPO_ORDEM_SERVICO", "DE_ETAPA", "NR_DIAS_UTEIS_DURACAO", "NR_ORDEM")
	VALUES (2, 'Sprint 4', 10, 5);
	INSERT INTO contractusapp."TB_ETAPA_TIPO_ORDEM_SERVICO_CONTRATO"(
	"ID_TIPO_ORDEM_SERVICO", "DE_ETAPA", "NR_DIAS_UTEIS_DURACAO", "NR_ORDEM")
	VALUES (2, 'Sprint 5', 10, 6);


	INSERT INTO contractusapp."TB_ETAPA_TIPO_ORDEM_SERVICO_CONTRATO"(
	"ID_TIPO_ORDEM_SERVICO", "DE_ETAPA", "NR_DIAS_UTEIS_DURACAO", "NR_ORDEM")
	VALUES (3, 'Sprint 0 - Iniciação', 5, 1);
	INSERT INTO contractusapp."TB_ETAPA_TIPO_ORDEM_SERVICO_CONTRATO"(
	"ID_TIPO_ORDEM_SERVICO", "DE_ETAPA", "NR_DIAS_UTEIS_DURACAO", "NR_ORDEM")
	VALUES (3, 'Sprint 1', 5, 2);
	INSERT INTO contractusapp."TB_ETAPA_TIPO_ORDEM_SERVICO_CONTRATO"(
	"ID_TIPO_ORDEM_SERVICO", "DE_ETAPA", "NR_DIAS_UTEIS_DURACAO", "NR_ORDEM")
	VALUES (3, 'Sprint 2', 5, 3);
	INSERT INTO contractusapp."TB_ETAPA_TIPO_ORDEM_SERVICO_CONTRATO"(
	"ID_TIPO_ORDEM_SERVICO", "DE_ETAPA", "NR_DIAS_UTEIS_DURACAO", "NR_ORDEM")
	VALUES (3, 'Sprint 3', 5, 4);

