version: '3.3'
services:
    postgresdb:
        image: fabianorodrigo/contractusapp-postgres:latest
        container_name: postgressdbcompose
        networks:
            - contractusnet
        ports:
            - '5432:5432'
        volumes:
            - postgresql:/var/lib/postgresql
            # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
            - postgresql_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=contractusapp
            - POSTGRES_PASSWORD=contractusapp
    contractus-app:
        image: fabianorodrigo/contractus-app:latest
        depends_on:
            - postgresdb
        ports:
            - '3000:3000'
        networks:
            - contractusnet
        environment:
            - sonar.jdbc.url=jdbc:postgresql://postgresdb:5432/contractus
            - POSTGRES_HOST=postgressdbcompose
        #command: sysctl -w vm.max_map_count=262144
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
            memlock:
                soft: -1
                hard: -1
        volumes:
            - contractus_conf:/opt/contractus/conf
volumes:
    postgresql:
    postgresql_data:
    contractus_conf:
networks:
    contractusnet:
        driver: bridge
